/** Plano de 14 dias e checklist final, derivados dos 19 passos do roadmap. */

export interface Step {
  id: string;
  n: number;
  letter: string;
  day: [number, number];
  title: string;
  action: string;
  why: string;
  example: string;
  pitfall: string;
  anchor?: string;
  moduleId: string;
}

export const STEPS: Step[] = [
  {
    id: 's1',
    n: 1,
    letter: 'V',
    day: [1, 3],
    title: 'Mapear redes, verticais e canais',
    action: 'Liste as redes acessíveis no seu país de residência e as verticais com comissão acima do seu piso.',
    why: 'Sem mapa, você escolhe rede por familiaridade, não por margem.',
    example: 'Amazon (1–20%), ClickBank (50–75% em digital), Impact (20–40% em software).',
    pitfall: 'Escolher a rede antes de escolher a oferta.',
    moduleId: 'demand',
  },
  {
    id: 's2',
    n: 2,
    letter: 'V',
    day: [1, 3],
    title: 'Verificar demanda e comissão',
    action: 'Confirme busca ativa e comissão que cubra o custo do clique.',
    why: 'Sem demanda não há conversão; sem margem não há lucro.',
    example: 'Meça volume de busca no país-alvo antes de abrir o gerenciador de anúncios.',
    pitfall: 'Confundir curiosidade com intenção de compra.',
    anchor: 'Benchmarks de CTR, CPA e EPC por vertical e canal.',
    moduleId: 'demand',
  },
  {
    id: 's3',
    n: 3,
    letter: 'A',
    day: [1, 3],
    title: 'Auditar concorrência e compliance',
    action: 'Analise 5 concorrentes diretos e leia as regras da rede.',
    why: 'Você precisa saber o que já está saturado e o que é proibido.',
    example: 'Anote os ângulos usados e as lacunas que ninguém cobriu.',
    pitfall: 'Copiar criativo alheio e violar direitos autorais.',
    moduleId: 'audit',
  },
  {
    id: 's4',
    n: 4,
    letter: 'V',
    day: [4, 6],
    title: 'Filtrar por demanda real',
    action: 'Verifique volume de busca e intenção de compra.',
    why: 'Produto sem demanda é produto sem campanha.',
    example: 'Curva de 12 meses no Trends separa demanda consistente de pico passageiro.',
    pitfall: 'Confundir tendência passageira com demanda consistente.',
    moduleId: 'demand',
  },
  {
    id: 's5',
    n: 5,
    letter: 'V',
    day: [4, 6],
    title: 'Calcular a comissão mínima viável',
    action: 'Divida a comissão pelo custo estimado do clique.',
    why: 'Se o clique custa mais que a comissão, você paga para trabalhar.',
    example: 'Comissão de US$ 12 e CPC de US$ 2 exigem 1 conversão a cada 6 cliques para empatar.',
    pitfall: 'Ignorar taxas da rede e impostos internacionais.',
    moduleId: 'demand',
  },
  {
    id: 's6',
    n: 6,
    letter: 'A',
    day: [4, 6],
    title: 'Verificar compliance e logística',
    action: 'Leia políticas da rede, leis do país-alvo e condições de entrega.',
    why: 'Campanha bloqueada ou produto não entregue = comissão perdida.',
    example: 'GDPR na Europa, FTC nos EUA, LGPD no Brasil.',
    pitfall: 'Assumir que as regras do seu país valem no exterior.',
    anchor: 'Políticas FTC, GDPR, LGPD e termos de ClickBank, Amazon Associates e Impact.',
    moduleId: 'audit',
  },
  {
    id: 's7',
    n: 7,
    letter: 'L',
    day: [7, 9],
    title: 'Definir o ângulo central',
    action: 'Escolha um único ângulo e construa tudo em volta dele.',
    why: 'Ângulo claro gera criativo claro, que gera clique qualificado.',
    example: '"Aposentadoria aos 40" é ângulo; "investimento" é tema.',
    pitfall: 'Misturar ângulos e confundir o algoritmo.',
    moduleId: 'angle',
  },
  {
    id: 's8',
    n: 8,
    letter: 'L',
    day: [7, 9],
    title: 'Montar o funil mínimo',
    action: 'Crie página de captura, página de venda e sequência de e-mails.',
    why: 'Funil simples converte mais que funil complexo.',
    example: 'Isca digital → e-mail → oferta.',
    pitfall: 'Enviar tráfego direto para a página da rede.',
    moduleId: 'angle',
  },
  {
    id: 's9',
    n: 9,
    letter: 'I',
    day: [7, 9],
    title: 'Configurar rastreamento completo',
    action: 'Instale pixel, parâmetros UTM e ferramenta de tracking.',
    why: 'Você precisa saber qual criativo, público e país convertem.',
    example: 'RedTrack ou Voluum integrados ao Google Ads.',
    pitfall: 'Rastrear só clique, não conversão.',
    anchor: 'Benchmarks de CTR por canal e geografia.',
    moduleId: 'tracking',
  },
  {
    id: 's10',
    n: 10,
    letter: 'I',
    day: [7, 9],
    title: 'Criar 3 variações de criativo por ângulo',
    action: 'Teste 3 imagens/vídeos com o mesmo ângulo.',
    why: 'O criativo certo pode dobrar o CTR.',
    example: 'Antes/depois, depoimento, demonstração.',
    pitfall: 'Mudar ângulo e criativo ao mesmo tempo.',
    moduleId: 'tracking',
  },
  {
    id: 's11',
    n: 11,
    letter: 'L',
    day: [1, 3],
    title: 'Escolher um canal principal',
    action: 'Selecione Google Ads, Meta Ads ou TikTok como canal principal.',
    why: 'Dominar um canal vale mais que estar em três.',
    example: 'Google para intenção de busca; Meta para descoberta; TikTok para volume.',
    pitfall: 'Rodar em todos e não otimizar nenhum.',
    moduleId: 'angle',
  },
  {
    id: 's12',
    n: 12,
    letter: 'L',
    day: [7, 9],
    title: 'Adaptar idioma e cultura',
    action: 'Localize copy, criativo e oferta para o país-alvo.',
    why: 'Tradução literal não vende; adaptação cultural vende.',
    example: 'Copy nativa ou revisor local.',
    pitfall: 'Assumir que inglês serve para todos os países.',
    anchor: 'Países permitidos e custos de tráfego por canal.',
    moduleId: 'angle',
  },
  {
    id: 's13',
    n: 13,
    letter: 'D',
    day: [10, 12],
    title: 'Definir o orçamento de teste',
    action: 'Estipule um valor que você aceita perder.',
    why: 'Teste não é aposta; é custo de aprendizado.',
    example: 'O maior entre o piso da plataforma, o da learning phase e o estatístico.',
    pitfall: 'Testar com valor que compromete o mês.',
    anchor: 'Orçamento mínimo viável por canal.',
    moduleId: 'decide',
  },
  {
    id: 's14',
    n: 14,
    letter: 'D',
    day: [10, 12],
    title: 'Rodar por 72 horas sem mexer',
    action: 'Deixe a campanha rodar sem alterações por 3 dias.',
    why: 'O algoritmo precisa de dados para otimizar.',
    example: '1.000 impressões mínimas por criativo.',
    pitfall: 'Pausar tudo na primeira hora.',
    moduleId: 'test72',
  },
  {
    id: 's15',
    n: 15,
    letter: 'D',
    day: [10, 12],
    title: 'Cortar com base nas métricas',
    action: 'Pause o que não bateu CTR, CPA ou EPC mínimo.',
    why: 'Manter campanha ruim é queimar verba.',
    example: 'CTR < 1% após 1.000 impressões = pause.',
    pitfall: 'Dar "mais uma chance" sem dado novo.',
    anchor: 'Tamanho de amostra mínimo e métricas de corte por canal.',
    moduleId: 'decide',
  },
  {
    id: 's16',
    n: 16,
    letter: 'A',
    day: [13, 14],
    title: 'Documentar o que funcionou',
    action: 'Registre ângulo, criativo, público, país e métricas.',
    why: 'O que não é documentado não é replicável.',
    example: 'Planilha ou dashboard com KPIs.',
    pitfall: 'Confiar na memória.',
    moduleId: 'export',
  },
  {
    id: 's17',
    n: 17,
    letter: 'A',
    day: [13, 14],
    title: 'Automatizar o que for repetível',
    action: 'Use automação para e-mails, relatórios e otimização.',
    why: 'Tempo é o ativo mais caro do afiliado.',
    example: 'Sequência de e-mails automatizada.',
    pitfall: 'Automatizar antes de validar.',
    moduleId: 'scale',
  },
  {
    id: 's18',
    n: 18,
    letter: 'A',
    day: [13, 14],
    title: 'Proteger o que você construiu',
    action: 'Regularize impostos, contratos e pagamentos internacionais.',
    why: 'Escala sem proteção legal vira problema.',
    example: 'CNPJ com CNAE correto, W-8BEN, contrato assinado.',
    pitfall: 'Ignorar obrigações fiscais.',
    anchor: 'Impostos para afiliados no exterior.',
    moduleId: 'audit',
  },
  {
    id: 's19',
    n: 19,
    letter: 'A',
    day: [13, 14],
    title: 'Escalar em degraus',
    action: 'Aumente o orçamento em 20% ao dia enquanto o CPA se mantiver.',
    why: 'Escala brusca quebra a campanha.',
    example: 'US$ 10 → US$ 12 → US$ 14,40.',
    pitfall: 'Dobrar orçamento de uma vez.',
    anchor: 'Casos de escala, impostos internacionais e contratos.',
    moduleId: 'scale',
  },
];

export const FINAL_CHECKLIST: Array<{ id: string; label: string; stepId: string }> = [
  { id: 'c1', label: 'Rede de afiliados escolhida', stepId: 's1' },
  { id: 'c2', label: 'Oferta validada por 4 filtros', stepId: 's5' },
  { id: 'c3', label: 'Compliance verificado', stepId: 's6' },
  { id: 'c4', label: 'Funil montado', stepId: 's8' },
  { id: 'c5', label: 'Rastreamento configurado', stepId: 's9' },
  { id: 'c6', label: 'Métricas de corte definidas', stepId: 's15' },
  { id: 'c7', label: 'Teste de 72 horas rodado', stepId: 's14' },
  { id: 'c8', label: 'Decisão de escala documentada', stepId: 's16' },
];

export const DAY_BLOCKS: Array<{ days: [number, number]; label: string; focus: string }> = [
  { days: [1, 3], label: 'Dias 1–3', focus: 'Mapear redes, verticais e canais.' },
  { days: [4, 6], label: 'Dias 4–6', focus: 'Aplicar filtros de oferta.' },
  { days: [7, 9], label: 'Dias 7–9', focus: 'Montar funil e rastreamento.' },
  { days: [10, 12], label: 'Dias 10–12', focus: 'Rodar teste de 72 horas.' },
  { days: [13, 14], label: 'Dias 13–14', focus: 'Cortar, ajustar e decidir escala.' },
];
